version: '3.6'
services:
  nc-nginx:
    networks:
      - default 
    image: mynginx
    container_name: mynginx
    restart: unless-stopped
    labels:
       - com.docker.stack.namespace=lsd
    ports:
       - '80:80'
       - '443:443'
       - '10380:80'
    volumes:
        - /mnt/e/blacklaptop/work/AWS_cloud/upwork/job5/nginx/static-build:/static-build
networks:
  docker_default:
    external: true
